const mongoose = require('mongoose');
const Product = require('../models/Product');
const User = require('../models/User');
const bcrypt = require('bcryptjs');
require('dotenv').config();

// Function to generate random discount between 2% and 25%
function generateRandomDiscount() {
  return Math.floor(Math.random() * 24) + 2; // Random number between 2 and 25
}

// Function to calculate prices based on discount
function calculatePrices(basePrice) {
  const discountPercentage = generateRandomDiscount();
  const initialPrice = basePrice;
  const highPrice = Math.round(basePrice * 1.3); // 30% higher than base price
  const offerPrice = Math.round(initialPrice * (1 - (discountPercentage / 100)));
  
  return {
    price: basePrice,
    initialPrice: initialPrice,
    highPrice: highPrice,
    offerPrice: offerPrice,
    discountPercentage: discountPercentage
  };
}

// Sample product data with guaranteed working images
const sampleProducts = [
  {
    name: 'iPhone 15 Pro',
    description: 'Latest iPhone with A17 Pro chip, titanium design, and advanced camera system',
    ...calculatePrices(79999),
    category: 'electronics',
    brand: 'Apple',
    images: [
      'https://images.unsplash.com/photo-1592287515832-053a17bfb967?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/4042807/pexels-photo-4042807.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/iphone-5584163_960_720.jpg'
    ],
    stock: 50,
    rating: 4.8,
    numReviews: 125,
    tags: ['smartphone', 'apple', 'premium', 'camera'],
    features: ['A17 Pro chip', 'Titanium design', 'Pro camera system', '5G'],
    aiRecommendationScore: 0.95,
    popularity: 89
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Premium Android smartphone with S Pen and advanced photography features',
    ...calculatePrices(95999),
    category: 'electronics',
    brand: 'Samsung',
    images: [
      'https://images.unsplash.com/photo-1580910059747-758a8db0c582?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/samsung-5584163_960_720.jpg'
    ],
    stock: 35,
    rating: 4.7,
    numReviews: 98,
    tags: ['smartphone', 'samsung', 'android', 's-pen'],
    features: ['S Pen included', '200MP camera', 'Galaxy AI', '5G'],
    aiRecommendationScore: 0.92,
    popularity: 85
  },
  {
    name: 'Nike Air Max 270',
    description: 'Comfortable running shoes with Max Air unit for superior cushioning',
    ...calculatePrices(9999),
    category: 'sports',
    brand: 'Nike',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/2529115/pexels-photo-2529115.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/nike-5584163_960_720.jpg'
    ],
    stock: 100,
    rating: 4.5,
    numReviews: 203,
    tags: ['shoes', 'running', 'nike', 'comfortable'],
    features: ['Max Air unit', 'Breathable mesh', 'Rubber outsole', 'Comfort fit'],
    aiRecommendationScore: 0.88,
    popularity: 92
  },
  {
    name: 'Adidas Ultraboost 22',
    description: 'High-performance running shoes with responsive Boost cushioning',
    ...calculatePrices(1241071),
    category: 'sports',
    brand: 'Adidas',
    images: ['https://images.unsplash.com/photo-1606107556191-b449b537af7f?w=300&h=300&fit=crop&crop=center'],
    stock: 75,
    rating: 4.6,
    numReviews: 156,
    tags: ['shoes', 'running', 'adidas', 'performance'],
    features: ['Boost cushioning', 'Primeknit upper', 'Continental rubber', 'Energy return'],
    aiRecommendationScore: 0.90,
    popularity: 88
  },
  {
    name: 'MacBook Pro 14"',
    description: 'Powerful laptop with M3 Pro chip, stunning Liquid Retina XDR display',
    ...calculatePrices(1389167),
    category: 'electronics',
    brand: 'Apple',
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/laptop-5584163_960_720.jpg'
    ],
    stock: 25,
    rating: 4.9,
    numReviews: 87,
    tags: ['laptop', 'apple', 'professional', 'm3'],
    features: ['M3 Pro chip', 'Liquid Retina XDR', '18-hour battery', 'Pro apps'],
    aiRecommendationScore: 0.96,
    popularity: 94
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    description: 'Premium noise-canceling headphones with exceptional sound quality',
    ...calculatePrices(33167),
    category: 'electronics',
    brand: 'Sony',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/headphones-5584163_960_720.jpg'
    ],
    stock: 60,
    rating: 4.7,
    numReviews: 234,
    tags: ['headphones', 'sony', 'noise-canceling', 'wireless'],
    features: ['Industry-leading noise canceling', '30-hour battery', 'Hi-Res Audio', 'Multi-device connection'],
    aiRecommendationScore: 0.91,
    popularity: 87
  },
  {
    name: 'The Great Gatsby',
    description: 'Classic American novel by F. Scott Fitzgerald',
    ...calculatePrices(1079),
    category: 'books',
    brand: 'Penguin Classics',
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d238f?w=300&h=300&fit=crop&crop=center'],
    stock: 200,
    rating: 4.4,
    numReviews: 567,
    tags: ['classic', 'fiction', 'american-literature', '1920s'],
    features: ['Classic literature', 'American fiction', '1920s setting', 'Romance'],
    aiRecommendationScore: 0.82,
    popularity: 79
  },
  {
    name: 'Smart Home Hub',
    description: 'Central control for all your smart home devices',
    ...calculatePrices(12367),
    category: 'home',
    brand: 'SmartHome',
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=center'],
    stock: 80,
    rating: 4.3,
    numReviews: 145,
    tags: ['smart-home', 'automation', 'iot', 'control'],
    features: ['Voice control', 'App control', 'Multi-device support', 'Automation'],
    aiRecommendationScore: 0.85,
    popularity: 72
  },
  {
    name: 'Yoga Mat Premium',
    description: 'Non-slip, eco-friendly yoga mat with extra cushioning',
    ...calculatePrices(3739),
    category: 'sports',
    brand: 'FitGear',
    images: ['https://images.unsplash.com/photo-1599458628178-a55d1e0aba85?w=300&h=300&fit=crop&crop=center'],
    stock: 150,
    rating: 4.6,
    numReviews: 189,
    tags: ['yoga', 'fitness', 'mat', 'eco-friendly'],
    features: ['Non-slip surface', 'Extra cushioning', 'Eco-friendly materials', 'Carrying strap'],
    aiRecommendationScore: 0.83,
    popularity: 76
  },
  {
    name: 'Organic Face Cream',
    description: 'Natural moisturizer for all skin types',
    ...calculatePrices(2324),
    category: 'beauty',
    brand: 'NatureGlow',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1a7f8d923?w=300&h=300&fit=crop&crop=center'],
    stock: 120,
    rating: 4.5,
    numReviews: 298,
    tags: ['skincare', 'organic', 'moisturizer', 'natural'],
    features: ['Organic ingredients', 'All skin types', 'Anti-aging', 'Dermatologist tested'],
    aiRecommendationScore: 0.86,
    popularity: 81
  },
  {
    name: 'LEGO Creator Expert',
    description: 'Advanced building set for adult collectors',
    ...calculatePrices(16567),
    category: 'toys',
    brand: 'LEGO',
    images: ['https://images.unsplash.com/photo-1598677359796-0d5d8e9c4b92?w=300&h=300&fit=crop&crop=center'],
    stock: 45,
    rating: 4.8,
    numReviews: 167,
    tags: ['lego', 'building', 'adults', 'collector'],
    features: ['3000+ pieces', 'Detailed design', 'Display stand', 'Instructions'],
    aiRecommendationScore: 0.89,
    popularity: 83
  },
  {
    name: 'Cotton T-Shirt Pack',
    description: 'Comfortable 100% cotton t-shirts in assorted colors, perfect for everyday wear',
    ...calculatePrices(2909),
    category: 'clothing',
    brand: 'BasicWear',
    images: ['https://images.unsplash.com/photo-1562157269-077c4e30c5a5?w=300&h=300&fit=crop&crop=center'],
    stock: 300,
    rating: 4.2,
    numReviews: 412,
    tags: ['t-shirt', 'cotton', 'casual', 'pack'],
    features: ['100% cotton', 'Machine washable', 'Assorted colors', 'Regular fit'],
    aiRecommendationScore: 0.78,
    popularity: 68
  },
  {
    name: 'iPad Pro 12.9"',
    description: 'Professional tablet with M2 chip, Liquid Retina XDR display, and Apple Pencil support',
    ...calculatePrices(91367),
    category: 'electronics',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3cd6773?w=300&h=300&fit=crop&crop=center'],
    stock: 30,
    rating: 4.7,
    numReviews: 156,
    tags: ['tablet', 'apple', 'professional', 'creative'],
    features: ['M2 chip', 'Liquid Retina XDR', 'Apple Pencil support', '5G'],
    aiRecommendationScore: 0.93,
    popularity: 91
  },
  {
    name: 'Google Pixel 8 Pro',
    description: 'Premium Android smartphone with advanced AI features and exceptional camera',
    ...calculatePrices(82967),
    category: 'electronics',
    brand: 'Google',
    images: ['https://images.unsplash.com/photo-1598322272224-7b80627a5e5a?w=300&h=300&fit=crop&crop=center'],
    stock: 40,
    rating: 4.6,
    numReviews: 189,
    tags: ['smartphone', 'google', 'android', 'camera'],
    features: ['Tensor G3 chip', 'AI photography', '7 years updates', 'Wireless charging'],
    aiRecommendationScore: 0.90,
    popularity: 85
  },
  {
    name: 'Dell XPS 15 Laptop',
    description: 'High-performance laptop with Intel Core i7, NVIDIA graphics, and 4K display',
    ...calculatePrices(1249173),
    category: 'electronics',
    brand: 'Dell',
    images: ['https://images.unsplash.com/photo-1593631214944-5a1c4b3c4b8c?w=300&h=300&fit=crop&crop=center'],
    stock: 20,
    rating: 4.5,
    numReviews: 98,
    tags: ['laptop', 'dell', 'professional', '4k'],
    features: ['Intel Core i7', 'NVIDIA RTX', '4K OLED display', 'Thunderbolt 4'],
    aiRecommendationScore: 0.88,
    popularity: 79
  },
  {
    name: 'AirPods Pro 2',
    description: 'Premium wireless earbuds with active noise cancellation and spatial audio',
    ...calculatePrices(20717),
    category: 'electronics',
    brand: 'Apple',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/headphones-5584163_960_720.jpg'
    ],
    stock: 80,
    rating: 4.4,
    numReviews: 445,
    tags: ['earbuds', 'apple', 'wireless', 'noise-canceling'],
    features: ['Active noise cancellation', 'Spatial audio', 'MagSafe charging', 'Sweat resistant'],
    aiRecommendationScore: 0.85,
    popularity: 88
  },
  {
    name: 'Samsung Galaxy Watch 6',
    description: 'Advanced smartwatch with health monitoring, GPS, and long battery life',
    ...calculatePrices(27317),
    category: 'electronics',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-157958575392-5c5b5c8b8c1b?w=300&h=300&fit=crop&crop=center'],
    stock: 60,
    rating: 4.3,
    numReviews: 167,
    tags: ['smartwatch', 'samsung', 'fitness', 'health'],
    features: ['Health monitoring', 'GPS tracking', 'Sleep analysis', 'Water resistant'],
    aiRecommendationScore: 0.82,
    popularity: 73
  },
  {
    name: 'Nike Air Jordan 1',
    description: 'Iconic basketball sneakers with classic design and premium materials',
    ...calculatePrices(117551),
    category: 'sports',
    brand: 'Nike',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/2529115/pexels-photo-2529115.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/nike-5584163_960_720.jpg'
    ],
    stock: 50,
    rating: 4.8,
    numReviews: 523,
    tags: ['shoes', 'basketball', 'nike', 'classic'],
    features: ['Premium leather', 'Air cushioning', 'Classic design', 'Limited edition'],
    aiRecommendationScore: 0.91,
    popularity: 95
  },
  {
    name: 'Adidas Stan Smith',
    description: 'Classic tennis shoes with minimalist style and comfortable fit',
    ...calculatePrices(58517),
    category: 'sports',
    brand: 'Adidas',
    images: ['https://images.unsplash.com/photo-1606107556191-b449b537af7f?w=300&h=300&fit=crop&crop=center'],
    stock: 120,
    rating: 4.4,
    numReviews: 289,
    tags: ['shoes', 'tennis', 'adidas', 'classic'],
    features: ['Leather upper', 'Rubber outsole', 'Classic design', 'Versatile'],
    aiRecommendationScore: 0.83,
    popularity: 81
  },
  {
    name: 'Puma RS-X',
    description: 'Retro-inspired running shoes with bold design and comfortable cushioning',
    ...calculatePrices(76019),
    category: 'sports',
    brand: 'Puma',
    images: ['https://images.unsplash.com/photo-1515954029468-8cde5c5cd5c5?w=300&h=300&fit=crop&crop=center'],
    stock: 90,
    rating: 4.2,
    numReviews: 156,
    tags: ['shoes', 'running', 'puma', 'retro'],
    features: ['RS foam cushioning', 'Mesh upper', 'Rubber outsole', 'Retro style'],
    aiRecommendationScore: 0.80,
    popularity: 76
  },
  {
    name: 'Under Armour Hoodie',
    description: 'Performance hoodie with moisture-wicking fabric and modern fit',
    ...calculatePrices(5417),
    category: 'clothing',
    brand: 'Under Armour',
    images: ['https://images.unsplash.com/photo-1551698638492-354a5b6c6c0c?w=300&h=300&fit=crop&crop=center'],
    stock: 150,
    rating: 4.3,
    numReviews: 198,
    tags: ['hoodie', 'athletic', 'under-armour', 'performance'],
    features: ['Moisture-wicking', 'Stretch fabric', 'Kangaroo pocket', 'Modern fit'],
    aiRecommendationScore: 0.81,
    popularity: 78
  },
  {
    name: 'Levi\'s 501 Jeans',
    description: 'Original straight-fit jeans with classic denim and timeless style',
    ...calculatePrices(7417),
    category: 'clothing',
    brand: 'Levi\'s',
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3242?w=300&h=300&fit=crop&crop=center'],
    stock: 200,
    rating: 4.6,
    numReviews: 634,
    tags: ['jeans', 'denim', 'levi\'s', 'classic'],
    features: ['100% cotton denim', 'Straight fit', 'Button fly', 'Classic styling'],
    aiRecommendationScore: 0.87,
    popularity: 92
  },
  {
    name: 'The Hobbit',
    description: 'J.R.R. Tolkien\'s classic fantasy adventure novel in deluxe edition',
    ...calculatePrices(2083),
    category: 'books',
    brand: 'Houghton Mifflin',
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=center'],
    stock: 150,
    rating: 4.7,
    numReviews: 892,
    tags: ['fantasy', 'adventure', 'tolkien', 'classic'],
    features: ['Deluxe edition', 'Illustrated', 'Hardcover', 'Collectible'],
    aiRecommendationScore: 0.89,
    popularity: 94
  },
  {
    name: '1984',
    description: 'George Orwell\'s dystopian masterpiece about totalitarian surveillance',
    ...calculatePrices(1249),
    category: 'books',
    brand: 'Signet Classics',
    images: ['https://images.unsplash.com/photo-1532011385631-9b9c6b6c6c6c?w=300&h=300&fit=crop&crop=center'],
    stock: 250,
    rating: 4.5,
    numReviews: 1245,
    tags: ['dystopian', 'classic', 'orwell', 'political'],
    features: ['Classic literature', 'Political commentary', 'Timeless themes', 'Mass market'],
    aiRecommendationScore: 0.86,
    popularity: 88
  },
  {
    name: 'Smart LED Bulbs (4-pack)',
    description: 'WiFi-enabled color-changing LED bulbs compatible with smart home systems',
    ...calculatePrices(6563),
    category: 'home',
    brand: 'SmartHome',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/headphones-5584163_960_720.jpg'
    ],
    stock: 100,
    rating: 4.1,
    numReviews: 267,
    tags: ['smart-home', 'lighting', 'wifi', 'color-changing'],
    features: ['WiFi enabled', '16 million colors', 'App control', 'Energy efficient'],
    aiRecommendationScore: 0.79,
    popularity: 71
  },
  {
    name: 'Robot Vacuum Cleaner',
    description: 'AI-powered robot vacuum with mapping technology and self-charging',
    ...calculatePrices(24817),
    category: 'home',
    brand: 'CleanBot',
    images: ['https://images.unsplash.com/photo-1558805933-6938b8b1d0c9?w=300&h=300&fit=crop&crop=center'],
    stock: 40,
    rating: 4.4,
    numReviews: 189,
    tags: ['vacuum', 'robot', 'smart-home', 'cleaning'],
    features: ['AI navigation', 'Self-charging', 'App control', 'Pet hair friendly'],
    aiRecommendationScore: 0.84,
    popularity: 82
  },
  {
    name: 'Resistance Bands Set',
    description: 'Professional-grade resistance bands for full-body workouts',
    ...calculatePrices(2417),
    category: 'sports',
    brand: 'FitGear',
    images: ['https://images.unsplash.com/photo-1606107556191-b449b537af7f?w=300&h=300&fit=crop&crop=center'],
    stock: 180,
    rating: 4.5,
    numReviews: 412,
    tags: ['fitness', 'resistance', 'workout', 'portable'],
    features: ['5 resistance levels', 'Non-slip handles', 'Portable case', 'Door anchor'],
    aiRecommendationScore: 0.83,
    popularity: 85
  },
  {
    name: 'Dumbbells Set (20lbs)',
    description: 'Adjustable dumbbell set with quick-change weight system',
    ...calculatePrices(7417),
    category: 'sports',
    brand: 'PowerFit',
    images: ['https://images.unsplash.com/photo-1585293920203-12b737f1f5f1?w=300&h=300&fit=crop&crop=center'],
    stock: 60,
    rating: 4.6,
    numReviews: 156,
    tags: ['weights', 'strength', 'adjustable', 'home-gym'],
    features: ['Adjustable weights', 'Ergonomic grip', 'Storage rack', 'Quick change'],
    aiRecommendationScore: 0.85,
    popularity: 79
  },
  {
    name: 'Vitamin C Serum',
    description: 'Brightening facial serum with 20% vitamin C and hyaluronic acid',
    ...calculatePrices(2659),
    category: 'beauty',
    brand: 'GlowSkin',
    images: ['https://images.unsplash.com/photo-1620916566398-49b5b6c6c6c6c?w=300&h=300&fit=crop&crop=center'],
    stock: 140,
    rating: 4.3,
    numReviews: 678,
    tags: ['skincare', 'serum', 'vitamin-c', 'anti-aging'],
    features: ['20% Vitamin C', 'Hyaluronic acid', 'Paraben-free', 'Dermatologist tested'],
    aiRecommendationScore: 0.82,
    popularity: 87
  },
  {
    name: 'Hydrating Face Mask',
    description: 'Deep hydration sheet mask with natural botanical extracts',
    ...calculatePrices(1499),
    category: 'beauty',
    brand: 'NatureGlow',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/2529115/pexels-photo-2529115.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/nike-5584163_960_720.jpg'
    ],
    stock: 300,
    rating: 4.4,
    numReviews: 445,
    tags: ['skincare', 'mask', 'hydration', 'natural'],
    features: ['Natural extracts', 'Deep hydration', 'Cruelty-free', '6-pack'],
    aiRecommendationScore: 0.81,
    popularity: 83
  },
  {
    name: 'LEGO Architecture Set',
    description: 'Build famous landmarks with detailed LEGO architecture sets',
    ...calculatePrices(12417),
    category: 'toys',
    brand: 'LEGO',
    images: ['https://images.unsplash.com/photo-1598677359796-0d5d8e9c4b92?w=300&h=300&fit=crop&crop=center'],
    stock: 35,
    rating: 4.7,
    numReviews: 234,
    tags: ['lego', 'architecture', 'building', 'educational'],
    features: ['Detailed design', 'Educational', 'Display quality', 'Collector item'],
    aiRecommendationScore: 0.88,
    popularity: 86
  },
  {
    name: 'Drone with Camera',
    description: 'HD camera drone with GPS, altitude hold, and 20-minute flight time',
    ...calculatePrices(15667),
    category: 'electronics',
    brand: 'SkyTech',
    images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=300&fit=crop&crop=center'],
    stock: 25,
    rating: 4.2,
    numReviews: 167,
    tags: ['drone', 'camera', 'gps', 'flying'],
    features: ['HD camera', 'GPS positioning', 'Altitude hold', '20 min flight time'],
    aiRecommendationScore: 0.80,
    popularity: 74
  },
  {
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices',
    ...calculatePrices(3239),
    category: 'electronics',
    brand: 'ChargeTech',
    images: ['https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=300&h=300&fit=crop&crop=center'],
    stock: 200,
    rating: 4.1,
    numReviews: 389,
    tags: ['charger', 'wireless', 'qi', 'fast-charging'],
    features: ['15W fast charging', 'Qi compatible', 'LED indicator', 'Safety protection'],
    aiRecommendationScore: 0.78,
    popularity: 77
  },
  {
    name: 'Microsoft Surface Pro 9',
    description: 'Versatile 2-in-1 tablet with laptop performance and tablet portability',
    ...calculatePrices(107917),
    category: 'electronics',
    brand: 'Microsoft',
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/laptop-5584163_960_720.jpg'
    ],
    stock: 35,
    rating: 4.5,
    numReviews: 234,
    tags: ['tablet', 'microsoft', '2-in-1', 'professional'],
    features: ['Intel Core i7', '13" touchscreen', 'All-day battery', 'Windows 11'],
    aiRecommendationScore: 0.87,
    popularity: 84
  },
  {
    name: 'Bose QuietComfort 45',
    description: 'Premium noise-canceling headphones with exceptional comfort and sound',
    ...calculatePrices(27317),
    category: 'electronics',
    brand: 'Bose',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/headphones-5584163_960_720.jpg'
    ],
    stock: 55,
    rating: 4.6,
    numReviews: 567,
    tags: ['headphones', 'bose', 'noise-canceling', 'comfort'],
    features: ['World-class noise cancellation', '24-hour battery', 'Comfortable fit', 'Clear calls'],
    aiRecommendationScore: 0.89,
    popularity: 91
  },
  {
    name: 'Fitbit Charge 6',
    description: 'Advanced fitness tracker with health monitoring and GPS',
    ...calculatePrices(13217),
    category: 'electronics',
    brand: 'Fitbit',
    images: ['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=300&h=300&fit=crop&crop=center'],
    stock: 120,
    rating: 4.3,
    numReviews: 445,
    tags: ['fitness', 'tracker', 'fitbit', 'health'],
    features: ['Built-in GPS', 'Heart rate monitoring', 'Sleep tracking', '7-day battery'],
    aiRecommendationScore: 0.83,
    popularity: 86
  },
  {
    name: 'Kindle Paperwhite',
    description: 'Waterproof e-reader with adjustable warm light and glare-free display',
    ...calculatePrices(11567),
    category: 'electronics',
    brand: 'Amazon',
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d238f?w=300&h=300&fit=crop&crop=center'],
    stock: 80,
    rating: 4.4,
    numReviews: 892,
    tags: ['e-reader', 'amazon', 'kindle', 'reading'],
    features: ['6.8" display', 'Waterproof design', 'Warm light', '8GB storage'],
    aiRecommendationScore: 0.85,
    popularity: 88
  },
  {
    name: 'JBL Flip 6 Speaker',
    description: 'Portable Bluetooth speaker with powerful sound and waterproof design',
    ...calculatePrices(9917),
    category: 'electronics',
    brand: 'JBL',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=300&h=300&fit=crop&crop=center'],
    stock: 150,
    rating: 4.2,
    numReviews: 334,
    tags: ['speaker', 'bluetooth', 'portable', 'waterproof'],
    features: ['12-hour battery', 'IP67 waterproof', 'PartyBoost', 'Compact design'],
    aiRecommendationScore: 0.80,
    popularity: 79
  },
  {
    name: 'Logitech MX Master 3S',
    description: 'Precision wireless mouse with ergonomic design and customizable buttons',
    ...calculatePrices(8239),
    category: 'electronics',
    brand: 'Logitech',
    images: ['https://images.unsplash.com/photo-1527864550417-7fd9fcf466c0?w=300&h=300&fit=crop&crop=center'],
    stock: 90,
    rating: 4.7,
    numReviews: 223,
    tags: ['mouse', 'wireless', 'ergonomic', 'productivity'],
    features: ['Quiet clicks', 'Ergonomic design', '70-day battery', 'Multi-device'],
    aiRecommendationScore: 0.86,
    popularity: 82
  },
  {
    name: 'Anker PowerCore 10000',
    description: 'Compact portable power bank with fast charging technology',
    ...calculatePrices(2417),
    category: 'electronics',
    brand: 'Anker',
    images: ['https://images.unsplash.com/photo-1585293920203-12b737f1f5f1?w=300&h=300&fit=crop&crop=center'],
    stock: 200,
    rating: 4.3,
    numReviews: 667,
    tags: ['power-bank', 'portable', 'anker', 'fast-charging'],
    features: ['10000mAh capacity', 'Fast charging', 'Compact size', 'Multi-protect'],
    aiRecommendationScore: 0.81,
    popularity: 85
  },
  {
    name: 'Garmin Forerunner 245',
    description: 'GPS running watch with advanced training metrics and health monitoring',
    ...calculatePrices(29017),
    category: 'electronics',
    brand: 'Garmin',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/2529115/pexels-photo-2529115.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/nike-5584163_960_720.jpg'
    ],
    stock: 40,
    rating: 4.5,
    numReviews: 189,
    tags: ['running-watch', 'gps', 'garmin', 'fitness'],
    features: ['GPS tracking', 'Heart rate monitor', 'Training metrics', '7-day battery'],
    aiRecommendationScore: 0.87,
    popularity: 78
  },
  {
    name: 'Nintendo Switch OLED',
    description: 'Premium gaming console with vibrant 7-inch OLED screen',
    ...calculatePrices(29017),
    category: 'electronics',
    brand: 'Nintendo',
    images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300&h=300&fit=crop&crop=center'],
    stock: 45,
    rating: 4.8,
    numReviews: 445,
    tags: ['gaming', 'nintendo', 'switch', 'portable'],
    features: ['7" OLED screen', '64GB storage', 'Enhanced audio', 'Wide stand'],
    aiRecommendationScore: 0.91,
    popularity: 93
  },
  {
    name: 'Reebok CrossFit Nano 8',
    description: 'CrossFit training shoes designed for high-intensity workouts',
    ...calculatePrices(10817),
    category: 'sports',
    brand: 'Reebok',
    images: ['https://images.unsplash.com/photo-1606107556191-b449b537af7f?w=300&h=300&fit=crop&crop=center'],
    stock: 70,
    rating: 4.4,
    numReviews: 156,
    tags: ['shoes', 'crossfit', 'training', 'reebok'],
    features: ['Flexweave upper', 'NanoShell', 'Toe reinforcement', 'Versatile training'],
    aiRecommendationScore: 0.83,
    popularity: 76
  },
  {
    name: 'New Balance 990v5',
    description: 'Classic running shoes with premium materials and modern comfort',
    ...calculatePrices(10417),
    category: 'sports',
    brand: 'New Balance',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/2529115/pexels-photo-2529115.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/nike-5584163_960_720.jpg'
    ],
    stock: 60,
    rating: 4.6,
    numReviews: 234,
    tags: ['shoes', 'running', 'new-balance', 'classic'],
    features: ['Premium suede', 'ENCAP midsole', 'Made in USA', 'Classic design'],
    aiRecommendationScore: 0.85,
    popularity: 81
  },
  {
    name: 'ASICS Gel-Kayano 29',
    description: 'Stability running shoes with advanced cushioning technology',
    ...calculatePrices(160),
    category: 'sports',
    brand: 'ASICS',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/2529115/pexels-photo-2529115.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/nike-5584163_960_720.jpg'
    ],
    stock: 55,
    rating: 4.5,
    numReviews: 189,
    tags: ['shoes', 'running', 'asics', 'stability'],
    features: ['GEL technology', 'FF BLAST cushioning', 'Guidance System', 'Breathable mesh'],
    aiRecommendationScore: 0.84,
    popularity: 79
  },
  {
    name: 'Wilson Pro Staff Tennis Racket',
    description: 'Professional tennis racket used by tour players worldwide',
    ...calculatePrices(229),
    category: 'sports',
    brand: 'Wilson',
    images: ['https://images.unsplash.com/photo-1596725337567-7cafd13df2fd?w=300&h=300&fit=crop&crop=center'],
    stock: 30,
    rating: 4.7,
    numReviews: 98,
    tags: ['tennis', 'racket', 'wilson', 'professional'],
    features: ['Graphite construction', 'Head-light balance', '16x19 string pattern', 'Pro feel'],
    aiRecommendationScore: 0.88,
    popularity: 83
  },
  {
    name: 'Spalding NBA Basketball',
    description: 'Official size and weight indoor basketball with superior grip',
    ...calculatePrices(5749),
    category: 'sports',
    brand: 'Spalding',
    images: ['https://images.unsplash.com/photo-1551698638492-354a5b6c6c0c?w=300&h=300&fit=crop&crop=center'],
    stock: 100,
    rating: 4.3,
    numReviews: 445,
    tags: ['basketball', 'spalding', 'nba', 'indoor'],
    features: ['Official size', 'ZK microfiber composite', 'Wide channel', 'Indoor use'],
    aiRecommendationScore: 0.81,
    popularity: 87
  },
  {
    name: 'Yonex Astrox 88D Badminton Racket',
    description: 'High-performance badminton racket for advanced players',
    ...calculatePrices(189),
    category: 'sports',
    brand: 'Yonex',
    images: ['https://images.unsplash.com/photo-1596725337567-7cafd13df2fd?w=300&h=300&fit=crop&crop=center'],
    stock: 25,
    rating: 4.6,
    numReviews: 67,
    tags: ['badminton', 'racket', 'yonex', 'advanced'],
    features: ['Isometric head', 'Nanomesh Neo', 'Rotational Generator System', 'Stiff shaft'],
    aiRecommendationScore: 0.86,
    popularity: 74
  },
  {
    name: 'Speedo Swim Goggles',
    description: 'Professional swimming goggles with anti-fog and UV protection',
    ...calculatePrices(24),
    category: 'sports',
    brand: 'Speedo',
    images: ['https://i.imgur.com/4L6mT5v.jpeg'],
    stock: 180,
    rating: 4.2,
    numReviews: 234,
    tags: ['swimming', 'goggles', 'speedo', 'professional'],
    features: ['Anti-fog coating', 'UV protection', 'Silicone seal', '4 interchangeable nose pieces'],
    aiRecommendationScore: 0.79,
    popularity: 81
  },
  {
    name: 'The North Face Backpack',
    description: 'Durable hiking backpack with 40L capacity and weather resistance',
    ...calculatePrices(149),
    category: 'sports',
    brand: 'The North Face',
    images: ['https://i.imgur.com/9NqK2Lm.jpeg'],
    stock: 45,
    rating: 4.7,
    numReviews: 189,
    tags: ['backpack', 'hiking', 'north-face', 'outdoor'],
    features: ['40L capacity', 'Water-resistant', 'Comfortable suspension', 'Multiple pockets'],
    aiRecommendationScore: 0.89,
    popularity: 85
  },
  {
    name: 'Columbia Rain Jacket',
    description: 'Waterproof breathable rain jacket for outdoor activities',
    ...calculatePrices(119),
    category: 'clothing',
    brand: 'Columbia',
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/laptop-5584163_960_720.jpg'
    ],
    stock: 80,
    rating: 4.4,
    numReviews: 267,
    tags: ['jacket', 'rain', 'columbia', 'outdoor'],
    features: ['Omni-Tech waterproof', 'Breathable', 'Packable', 'Adjustable hood'],
    aiRecommendationScore: 0.83,
    popularity: 82
  },
  {
    name: 'Patagonia Fleece Jacket',
    description: 'Sustainable fleece jacket made from recycled materials',
    ...calculatePrices(99),
    category: 'clothing',
    brand: 'Patagonia',
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d238f?w=300&h=300&fit=crop&crop=center'],
    stock: 60,
    rating: 4.6,
    numReviews: 345,
    tags: ['jacket', 'fleece', 'patagonia', 'sustainable'],
    features: ['Recycled polyester', 'Full-zip', 'Zippered pockets', 'Fair Trade Certified'],
    aiRecommendationScore: 0.87,
    popularity: 88
  },
  {
    name: 'Merino Wool Sweater',
    description: 'Premium merino wool sweater for warmth and comfort',
    ...calculatePrices(139),
    category: 'clothing',
    brand: 'SmartWool',
    images: ['https://i.imgur.com/4L6mT5v.jpeg'],
    stock: 40,
    rating: 4.5,
    numReviews: 156,
    tags: ['sweater', 'wool', 'merino', 'warm'],
    features: ['100% merino wool', 'Temperature regulation', 'Odor resistance', 'Machine washable'],
    aiRecommendationScore: 0.84,
    popularity: 79
  },
  {
    name: 'Cargo Pants',
    description: 'Durable cargo pants with multiple pockets for utility',
    ...calculatePrices(79),
    category: 'clothing',
    brand: 'Carhartt',
    images: ['https://picsum.photos/seed/cargopants/300/300.jpg'],
    stock: 120,
    rating: 4.3,
    numReviews: 234,
    tags: ['pants', 'cargo', 'carhartt', 'utility'],
    features: ['Heavy-duty cotton', '8 pockets', 'Reinforced knees', 'Relaxed fit'],
    aiRecommendationScore: 0.81,
    popularity: 76
  },
  {
    name: 'Polo Shirt',
    description: 'Classic polo shirt in pique cotton with embroidered logo',
    ...calculatePrices(45),
    category: 'clothing',
    brand: 'Ralph Lauren',
    images: ['https://picsum.photos/seed/poloshirt/300/300.jpg'],
    stock: 150,
    rating: 4.4,
    numReviews: 456,
    tags: ['polo', 'shirt', 'ralph-lauren', 'classic'],
    features: ['Pique cotton', 'Embroidered logo', 'Ribbed collar', 'Side vents'],
    aiRecommendationScore: 0.83,
    popularity: 84
  },
  {
    name: 'Wool Coat',
    description: 'Elegant wool coat for cold weather with timeless style',
    ...calculatePrices(299),
    category: 'clothing',
    brand: 'Burberry',
    images: ['https://picsum.photos/seed/woolcoat/300/300.jpg'],
    stock: 25,
    rating: 4.8,
    numReviews: 89,
    tags: ['coat', 'wool', 'burberry', 'elegant'],
    features: ['100% wool', 'Double-breasted', 'Notch lapels', 'Side pockets'],
    aiRecommendationScore: 0.92,
    popularity: 91
  },
  {
    name: 'To Kill a Mockingbird',
    description: 'Harper Lee\'s timeless classic about racial injustice in the American South',
    ...calculatePrices(1699),
    category: 'books',
    brand: 'Harper Perennial',
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d238f?w=300&h=300&fit=crop&crop=center'],
    stock: 200,
    rating: 4.8,
    numReviews: 1567,
    tags: ['classic', 'fiction', 'american-literature', 'social-justice'],
    features: ['Modern Classic', 'Social commentary', 'Coming-of-age', 'Pulitzer Prize winner'],
    aiRecommendationScore: 0.91,
    popularity: 95
  },
  {
    name: 'Pride and Prejudice',
    description: 'Jane Austen\'s romantic masterpiece about love and social class',
    ...calculatePrices(1299),
    category: 'books',
    brand: 'Penguin Classics',
    images: ['https://images.unsplash.com/photo-1481620733598-5cc4c0b622ab?w=300&h=300&fit=crop&crop=center'],
    stock: 180,
    rating: 4.6,
    numReviews: 892,
    tags: ['romance', 'classic', 'austen', 'british-literature'],
    features: ['Classic romance', 'Social commentary', 'Timeless themes', 'Annotated edition'],
    aiRecommendationScore: 0.87,
    popularity: 89
  },
  {
    name: 'The Catcher in the Rye',
    description: 'J.D. Salinger\'s iconic novel about teenage rebellion and alienation',
    ...calculatePrices(1499),
    category: 'books',
    brand: 'Little Brown',
    images: ['https://picsum.photos/seed/catcher/300/300.jpg'],
    stock: 150,
    rating: 4.3,
    numReviews: 1234,
    tags: ['classic', 'fiction', 'coming-of-age', 'american-literature'],
    features: ['Contemporary Classic', 'Teen protagonist', 'Social critique', 'Cultural impact'],
    aiRecommendationScore: 0.84,
    popularity: 86
  },
  {
    name: 'Harry Potter Series Set',
    description: 'Complete 7-book set of the magical Harry Potter series',
    ...calculatePrices(9999),
    category: 'books',
    brand: 'Scholastic',
    images: ['https://picsum.photos/seed/harrypotter/300/300.jpg'],
    stock: 50,
    rating: 4.9,
    numReviews: 2345,
    tags: ['fantasy', 'magic', 'series', 'children'],
    features: ['Complete series', 'Hardcover set', 'Collectible', 'Worldwide phenomenon'],
    aiRecommendationScore: 0.95,
    popularity: 98
  },
  {
    name: 'Coffee Table Book Collection',
    description: 'Beautiful photography books on travel, nature, and architecture',
    ...calculatePrices(149),
    category: 'books',
    brand: 'National Geographic',
    images: ['https://picsum.photos/seed/coffeetable/300/300.jpg'],
    stock: 35,
    rating: 4.5,
    numReviews: 167,
    tags: ['photography', 'travel', 'nature', 'coffee-table'],
    features: ['High-quality photos', 'Large format', 'Gift-worthy', 'Visual journey'],
    aiRecommendationScore: 0.85,
    popularity: 81
  },
  {
    name: 'Mystery Novel Set',
    description: 'Bestselling mystery novels collection from renowned authors',
    ...calculatePrices(4999),
    category: 'books',
    brand: 'Penguin Random House',
    images: ['https://picsum.photos/seed/mysterynovels/300/300.jpg'],
    stock: 55,
    rating: 4.4,
    numReviews: 234,
    tags: ['mystery', 'novels', 'bestsellers', 'collection'],
    features: ['5 novels', 'Award-winning authors', 'Page-turning plots', 'Collector\'s edition'],
    aiRecommendationScore: 0.81,
    popularity: 82
  },
  {
    name: 'Smart Thermostat',
    description: 'WiFi-enabled smart thermostat with energy-saving features',
    ...calculatePrices(199),
    category: 'home',
    brand: 'Nest',
    images: ['https://picsum.photos/seed/thermostat/300/300.jpg'],
    stock: 40,
    rating: 4.6,
    numReviews: 445,
    tags: ['thermostat', 'smart-home', 'nest', 'energy-saving'],
    features: ['Learning algorithm', 'Remote control', 'Energy reports', 'Voice control'],
    aiRecommendationScore: 0.88,
    popularity: 92
  },
  {
    name: 'Security Camera System',
    description: '4K security camera system with night vision and mobile app',
    ...calculatePrices(399),
    category: 'home',
    brand: 'Ring',
    images: ['https://picsum.photos/seed/securitycam/300/300.jpg'],
    stock: 30,
    rating: 4.4,
    numReviews: 234,
    tags: ['security', 'camera', 'ring', 'surveillance'],
    features: ['4K resolution', 'Night vision', 'Motion detection', 'Two-way audio'],
    aiRecommendationScore: 0.84,
    popularity: 85
  },
  {
    name: 'Air Purifier',
    description: 'HEPA air purifier for large rooms with smart sensors',
    ...calculatePrices(249),
    category: 'home',
    brand: 'Dyson',
    images: ['https://picsum.photos/seed/airpurifier/300/300.jpg'],
    stock: 35,
    rating: 4.5,
    numReviews: 345,
    tags: ['air-purifier', 'hepa', 'dyson', 'allergy'],
    features: ['HEPA filtration', 'Smart sensors', 'Quiet operation', 'Large coverage'],
    aiRecommendationScore: 0.86,
    popularity: 88
  },
  {
    name: 'Espresso Machine',
    description: 'Semi-automatic espresso machine with built-in grinder',
    ...calculatePrices(599),
    category: 'home',
    brand: 'DeLonghi',
    images: ['https://picsum.photos/seed/espresso/300/300.jpg'],
    stock: 20,
    rating: 4.7,
    numReviews: 189,
    tags: ['coffee', 'espresso', 'delonghi', 'kitchen'],
    features: ['Built-in grinder', 'Milk frother', 'Programmable', 'Compact design'],
    aiRecommendationScore: 0.90,
    popularity: 83
  },
  {
    name: 'Standing Desk Converter',
    description: 'Adjustable standing desk converter for ergonomic workspace',
    ...calculatePrices(349),
    category: 'home',
    brand: 'Varidesk',
    images: ['https://picsum.photos/seed/standingdesk/300/300.jpg'],
    stock: 45,
    rating: 4.3,
    numReviews: 267,
    tags: ['desk', 'standing', 'ergonomic', 'office'],
    features: ['Height adjustable', 'Spacious surface', 'Easy transition', 'Sturdy construction'],
    aiRecommendationScore: 0.81,
    popularity: 79
  },
  {
    name: 'Foam Roller',
    description: 'High-density foam roller for muscle recovery and flexibility',
    ...calculatePrices(25),
    category: 'sports',
    brand: 'TriggerPoint',
    images: ['https://picsum.photos/seed/foamroller/300/300.jpg'],
    stock: 160,
    rating: 4.4,
    numReviews: 345,
    tags: ['fitness', 'recovery', 'foam-roller', 'muscle'],
    features: ['High-density foam', 'Textured surface', 'Lightweight', 'Portable'],
    aiRecommendationScore: 0.82,
    popularity: 84
  },
  {
    name: 'Jump Rope',
    description: 'Speed jump rope with ball bearings for smooth rotation',
    ...calculatePrices(15),
    category: 'sports',
    brand: 'CrossRope',
    images: ['https://picsum.photos/seed/jumprope/300/300.jpg'],
    stock: 200,
    rating: 4.2,
    numReviews: 189,
    tags: ['fitness', 'jump-rope', 'cardio', 'portable'],
    features: ['Ball bearings', 'Adjustable length', 'Comfortable grips', 'Fast rotation'],
    aiRecommendationScore: 0.79,
    popularity: 77
  },
  {
    name: 'Exercise Ball',
    description: 'Anti-burst exercise ball for core strength and stability training',
    ...calculatePrices(22),
    category: 'sports',
    brand: 'TheraBand',
    images: ['https://picsum.photos/seed/exerciseball/300/300.jpg'],
    stock: 120,
    rating: 4.3,
    numReviews: 234,
    tags: ['fitness', 'exercise-ball', 'core', 'stability'],
    features: ['Anti-burst material', 'Non-slip surface', 'Multiple sizes', 'Inflation pump included'],
    aiRecommendationScore: 0.80,
    popularity: 81
  },
  {
    name: 'Kettlebell Set',
    description: 'Cast iron kettlebell set for strength training and conditioning',
    ...calculatePrices(89),
    category: 'sports',
    brand: 'CAP Barbell',
    images: ['https://picsum.photos/seed/kettlebell/300/300.jpg'],
    stock: 40,
    rating: 4.5,
    numReviews: 156,
    tags: ['weights', 'kettlebell', 'strength', 'cast-iron'],
    features: ['Cast iron construction', 'Wide handle', 'Powder coating', 'Multiple weights'],
    aiRecommendationScore: 0.84,
    popularity: 78
  },
  {
    name: 'Retinol Cream',
    description: 'Anti-aging retinol cream for smooth, youthful skin',
    ...calculatePrices(45),
    category: 'beauty',
    brand: 'SkinCeuticals',
    images: ['https://picsum.photos/seed/retinol/300/300.jpg'],
    stock: 60,
    rating: 4.4,
    numReviews: 567,
    tags: ['skincare', 'retinol', 'anti-aging', 'dermatology'],
    features: ['0.3% retinol', 'Hyaluronic acid', 'Fragrance-free', 'Dermatologist recommended'],
    aiRecommendationScore: 0.85,
    popularity: 89
  },
  {
    name: 'Sunscreen SPF 50',
    description: 'Broad-spectrum sunscreen with SPF 50 for maximum protection',
    ...calculatePrices(28),
    category: 'beauty',
    brand: 'La Roche-Posay',
    images: ['https://picsum.photos/seed/sunscreen/300/300.jpg'],
    stock: 180,
    rating: 4.6,
    numReviews: 892,
    tags: ['sunscreen', 'spf', 'protection', 'dermatology'],
    features: ['SPF 50+', 'Broad spectrum', 'Water resistant', 'Non-comedogenic'],
    aiRecommendationScore: 0.87,
    popularity: 92
  },
  {
    name: 'Eye Cream',
    description: 'Revitalizing eye cream to reduce dark circles and fine lines',
    ...calculatePrices(52),
    category: 'beauty',
    brand: 'Kiehl\'s',
    images: ['https://picsum.photos/seed/eyecream/300/300.jpg'],
    stock: 70,
    rating: 4.3,
    numReviews: 345,
    tags: ['skincare', 'eye-cream', 'anti-aging', 'dark-circles'],
    features: ['Vitamin C', 'Caffeine', 'Hyaluronic acid', 'Dermatologist tested'],
    aiRecommendationScore: 0.82,
    popularity: 85
  },
  {
    name: 'Lip Balm Set',
    description: 'Moisturizing lip balm set with natural flavors and SPF protection',
    ...calculatePrices(18),
    category: 'beauty',
    brand: 'Burt\'s Bees',
    images: ['https://picsum.photos/seed/lipbalm/300/300.jpg'],
    stock: 250,
    rating: 4.2,
    numReviews: 678,
    tags: ['lip-balm', 'moisturizing', 'natural', 'spf'],
    features: ['Natural ingredients', 'SPF 15', 'Multiple flavors', 'Beeswax formula'],
    aiRecommendationScore: 0.79,
    popularity: 87
  },
  {
    name: 'Board Game Collection',
    description: 'Strategy board game collection for family game nights',
    ...calculatePrices(79),
    category: 'toys',
    brand: 'Hasbro',
    images: ['https://picsum.photos/seed/boardgames/300/300.jpg'],
    stock: 60,
    rating: 4.5,
    numReviews: 234,
    tags: ['board-games', 'family', 'strategy', 'collection'],
    features: ['Multiple games', 'Family-friendly', 'Educational', 'High quality'],
    aiRecommendationScore: 0.84,
    popularity: 81
  },
  {
    name: 'Art Supplies Set',
    description: 'Professional art supplies set for drawing and painting',
    ...calculatePrices(129),
    category: 'toys',
    brand: 'Faber-Castell',
    images: ['https://picsum.photos/seed/artsupplies/300/300.jpg'],
    stock: 35,
    rating: 4.6,
    numReviews: 167,
    tags: ['art', 'drawing', 'painting', 'professional'],
    features: ['120 pencils', 'Watercolor paints', 'Brushes', 'Carrying case'],
    aiRecommendationScore: 0.86,
    popularity: 78
  },
  {
    name: 'Puzzle Collection',
    description: '1000-piece jigsaw puzzles with beautiful landscape designs',
    ...calculatePrices(24),
    category: 'toys',
    brand: 'Ravensburger',
    images: ['https://picsum.photos/seed/puzzles/300/300.jpg'],
    stock: 90,
    rating: 4.4,
    numReviews: 345,
    tags: ['puzzle', 'jigsaw', 'landscape', 'family'],
    features: ['1000 pieces', 'High-quality cardboard', 'Beautiful designs', 'Frame-worthy'],
    aiRecommendationScore: 0.81,
    popularity: 83
  },
  {
    name: 'Remote Control Car',
    description: 'High-speed remote control car with rechargeable battery',
    ...calculatePrices(89),
    category: 'toys',
    brand: 'Traxxas',
    images: ['https://picsum.photos/seed/rccar/300/300.jpg'],
    stock: 40,
    rating: 4.3,
    numReviews: 189,
    tags: ['rc-car', 'remote-control', 'toy', 'high-speed'],
    features: ['30 mph top speed', 'Rechargeable battery', 'All-terrain tires', '2.4GHz control'],
    aiRecommendationScore: 0.80,
    popularity: 76
  },
  {
    name: 'Musical Instrument Set',
    description: 'Children\'s musical instrument set for early music education',
    ...calculatePrices(49),
    category: 'toys',
    brand: 'Melissa & Doug',
    images: ['https://picsum.photos/seed/musicset/300/300.jpg'],
    stock: 70,
    rating: 4.5,
    numReviews: 267,
    tags: ['musical', 'instruments', 'children', 'educational'],
    features: ['17 instruments', 'Wooden construction', 'Storage crate', 'Educational value'],
    aiRecommendationScore: 0.84,
    popularity: 82
  },
  {
    name: 'Science Kit',
    description: 'STEM science kit with 50+ experiments for curious minds',
    ...calculatePrices(39),
    category: 'toys',
    brand: 'National Geographic',
    images: ['https://picsum.photos/seed/sciencekit/300/300.jpg'],
    stock: 80,
    rating: 4.6,
    numReviews: 345,
    tags: ['science', 'stem', 'educational', 'experiments'],
    features: ['50+ experiments', 'Detailed guide', 'Safe materials', 'Award-winning'],
    aiRecommendationScore: 0.86,
    popularity: 88
  },
  {
    name: 'Action Figure Collection',
    description: 'Collectible action figures with detailed articulation',
    ...calculatePrices(159),
    category: 'toys',
    brand: 'Hasbro',
    images: ['https://picsum.photos/seed/actionfigures/300/300.jpg'],
    stock: 30,
    rating: 4.7,
    numReviews: 156,
    tags: ['action-figures', 'collectible', 'detailed', 'articulation'],
    features: ['6-inch scale', '20+ articulation points', 'Accessories included', 'Collector packaging'],
    aiRecommendationScore: 0.88,
    popularity: 85
  },
  {
    name: 'Building Blocks Set',
    description: 'Creative building blocks set for imaginative construction',
    ...calculatePrices(34),
    category: 'toys',
    brand: 'Mega Bloks',
    images: ['https://picsum.photos/seed/blocks/300/300.jpg'],
    stock: 120,
    rating: 4.3,
    numReviews: 234,
    tags: ['building-blocks', 'creative', 'construction', 'children'],
    features: ['500+ pieces', 'Multiple colors', 'Compatible with major brands', 'Storage bag'],
    aiRecommendationScore: 0.80,
    popularity: 79
  },
  {
    name: 'Outdoor Playhouse',
    description: 'Children\'s outdoor playhouse with slide and swing set',
    ...calculatePrices(599),
    category: 'toys',
    brand: 'Step2',
    images: ['https://picsum.photos/seed/playhouse/300/300.jpg'],
    stock: 15,
    rating: 4.5,
    numReviews: 89,
    tags: ['playhouse', 'outdoor', 'children', 'playground'],
    features: ['Slide included', 'Swing set', 'Weather-resistant', 'Easy assembly'],
    aiRecommendationScore: 0.85,
    popularity: 81
  },
  {
    name: 'Gaming Keyboard RGB',
    description: 'Mechanical gaming keyboard with RGB backlighting and programmable keys',
    ...calculatePrices(149),
    category: 'electronics',
    brand: 'Corsair',
    images: ['https://picsum.photos/seed/gamingkeyboard/300/300.jpg'],
    stock: 45,
    rating: 4.6,
    numReviews: 234,
    tags: ['keyboard', 'gaming', 'mechanical', 'rgb'],
    features: ['Cherry MX switches', 'RGB backlighting', 'Programmable keys', 'Aluminum frame'],
    aiRecommendationScore: 0.86,
    popularity: 84
  },
  {
    name: 'Gaming Mouse Wireless',
    description: 'High-precision wireless gaming mouse with 16000 DPI sensor',
    ...calculatePrices(99),
    category: 'electronics',
    brand: 'Logitech',
    images: ['https://picsum.photos/seed/gamingmouse/300/300.jpg'],
    stock: 60,
    rating: 4.5,
    numReviews: 345,
    tags: ['mouse', 'gaming', 'wireless', 'high-precision'],
    features: ['16000 DPI', 'Wireless charging', '11 programmable buttons', 'Ergonomic design'],
    aiRecommendationScore: 0.84,
    popularity: 87
  },
  {
    name: '4K Webcam',
    description: 'Professional 4K webcam for streaming and video conferencing',
    ...calculatePrices(179),
    category: 'electronics',
    brand: 'Razer',
    images: ['https://images.unsplash.com/photo-1596725337567-7cafd13df2fd?w=300&h=300&fit=crop&crop=center'],
    stock: 35,
    rating: 4.4,
    numReviews: 167,
    tags: ['webcam', '4k', 'streaming', 'video-conferencing'],
    features: ['4K resolution', 'Auto-focus', 'Noise cancellation', 'Wide-angle lens'],
    aiRecommendationScore: 0.82,
    popularity: 79
  },
  {
    name: 'USB-C Hub',
    description: '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader',
    ...calculatePrices(49),
    category: 'electronics',
    brand: 'Anker',
    images: ['https://picsum.photos/seed/usbhub/300/300.jpg'],
    stock: 120,
    rating: 4.3,
    numReviews: 456,
    tags: ['usb-hub', 'usb-c', 'multiport', 'connectivity'],
    features: ['7 ports', '4K HDMI output', '100W power delivery', 'Compact design'],
    aiRecommendationScore: 0.80,
    popularity: 82
  },
  {
    name: 'Wireless Earbuds',
    description: 'True wireless earbuds with active noise cancellation',
    ...calculatePrices(129),
    category: 'electronics',
    brand: 'Jabra',
    images: ['https://picsum.photos/seed/wirelessbuds/300/300.jpg'],
    stock: 80,
    rating: 4.2,
    numReviews: 289,
    tags: ['earbuds', 'wireless', 'noise-canceling', 'true-wireless'],
    features: ['Active noise cancellation', '8-hour battery', 'IPX4 rating', 'Wireless charging case'],
    aiRecommendationScore: 0.79,
    popularity: 76
  },
  {
    name: 'Smart Watch',
    description: 'Fitness-focused smartwatch with heart rate monitoring and GPS',
    ...calculatePrices(199),
    category: 'electronics',
    brand: 'Garmin',
    images: ['https://picsum.photos/seed/smartwatch/300/300.jpg'],
    stock: 55,
    rating: 4.4,
    numReviews: 198,
    tags: ['smartwatch', 'fitness', 'gps', 'heart-rate'],
    features: ['Built-in GPS', 'Heart rate monitor', 'Sleep tracking', 'Water resistant'],
    aiRecommendationScore: 0.82,
    popularity: 83
  },
  {
    name: 'Tablet Stand',
    description: 'Adjustable aluminum tablet stand for desk and lap use',
    ...calculatePrices(39),
    category: 'electronics',
    brand: 'Lamicall',
    images: ['https://picsum.photos/seed/tabletstand/300/300.jpg'],
    stock: 150,
    rating: 4.3,
    numReviews: 234,
    tags: ['tablet-stand', 'aluminum', 'adjustable', 'desk-accessory'],
    features: ['Adjustable angles', 'Stable base', 'Non-slip pads', 'Portable design'],
    aiRecommendationScore: 0.80,
    popularity: 78
  },
  {
    name: 'Running Shorts',
    description: 'Lightweight running shorts with moisture-wicking fabric',
    ...calculatePrices(35),
    category: 'clothing',
    brand: 'Nike',
    images: ['https://picsum.photos/seed/runningshorts/300/300.jpg'],
    stock: 180,
    rating: 4.4,
    numReviews: 345,
    tags: ['shorts', 'running', 'athletic', 'moisture-wicking'],
    features: ['Dri-FIT fabric', 'Inner brief', 'Zippered pocket', 'Reflective details'],
    aiRecommendationScore: 0.82,
    popularity: 85
  },
  {
    name: 'Sports Bra',
    description: 'High-support sports bra for medium-impact activities',
    ...calculatePrices(45),
    category: 'clothing',
    brand: 'Under Armour',
    images: ['https://picsum.photos/seed/sportsbra/300/300.jpg'],
    stock: 120,
    rating: 4.3,
    numReviews: 267,
    tags: ['sports-bra', 'athletic', 'support', 'under-armour'],
    features: ['Medium support', 'Moisture-wicking', '4-way stretch', 'Padded straps'],
    aiRecommendationScore: 0.81,
    popularity: 81
  },
  {
    name: 'Winter Gloves',
    description: 'Insulated winter gloves with touchscreen compatibility',
    ...calculatePrices(29),
    category: 'clothing',
    brand: 'The North Face',
    images: ['https://picsum.photos/seed/wintergloves/300/300.jpg'],
    stock: 100,
    rating: 4.2,
    numReviews: 189,
    tags: ['gloves', 'winter', 'insulated', 'touchscreen'],
    features: ['Thinsulate insulation', 'Touchscreen compatible', 'Water-resistant', 'Grip palms'],
    aiRecommendationScore: 0.79,
    popularity: 77
  },
  {
    name: 'Hiking Boots',
    description: 'Waterproof hiking boots with excellent traction and support',
    ...calculatePrices(139),
    category: 'clothing',
    brand: 'Merrell',
    images: ['https://picsum.photos/seed/hikingboots/300/300.jpg'],
    stock: 60,
    rating: 4.5,
    numReviews: 234,
    tags: ['boots', 'hiking', 'waterproof', 'outdoor'],
    features: ['Waterproof leather', 'Vibram outsole', 'Cushioned midsole', 'Ankle support'],
    aiRecommendationScore: 0.85,
    popularity: 83
  },
  {
    name: 'Cookbook Collection',
    description: 'International cuisine cookbook collection with 500+ recipes',
    ...calculatePrices(59),
    category: 'books',
    brand: 'America\'s Test Kitchen',
    images: ['https://picsum.photos/seed/cookbook/300/300.jpg'],
    stock: 70,
    rating: 4.6,
    numReviews: 156,
    tags: ['cookbook', 'recipes', 'international', 'cooking'],
    features: ['500+ recipes', 'Step-by-step photos', 'Nutritional info', 'Beginner-friendly'],
    aiRecommendationScore: 0.84,
    popularity: 79
  },
  {
    name: 'Mystery Novel Set',
    description: 'Bestselling mystery novels collection from renowned authors',
    ...calculatePrices(4999),
    category: 'books',
    brand: 'Penguin Random House',
    images: ['https://picsum.photos/seed/mysterynovels/300/300.jpg'],
    stock: 55,
    rating: 4.4,
    numReviews: 234,
    tags: ['mystery', 'novels', 'bestsellers', 'collection'],
    features: ['5 novels', 'Award-winning authors', 'Page-turning plots', 'Collector\'s edition'],
    aiRecommendationScore: 0.81,
    popularity: 82
  },
  {
    name: 'Smart Doorbell',
    description: 'Video doorbell with motion detection and two-way audio',
    ...calculatePrices(199),
    category: 'home',
    brand: 'Ring',
    images: ['https://picsum.photos/seed/doorbell/300/300.jpg'],
    stock: 40,
    rating: 4.3,
    numReviews: 345,
    tags: ['doorbell', 'smart-home', 'video', 'security'],
    features: ['1080p HD video', 'Motion detection', 'Two-way audio', 'Night vision'],
    aiRecommendationScore: 0.82,
    popularity: 86
  },
  {
    name: 'Smart Lock',
    description: 'Keyless smart door lock with fingerprint and app control',
    ...calculatePrices(249),
    category: 'home',
    brand: 'August',
    images: ['https://picsum.photos/seed/smartlock/300/300.jpg'],
    stock: 30,
    rating: 4.4,
    numReviews: 189,
    tags: ['smart-lock', 'keyless', 'fingerprint', 'security'],
    features: ['Fingerprint sensor', 'App control', 'Auto-lock', 'Guest access'],
    aiRecommendationScore: 0.84,
    popularity: 81
  },
  {
    name: 'Electric Toothbrush',
    description: 'Sonic electric toothbrush with pressure sensor and timer',
    ...calculatePrices(79),
    category: 'home',
    brand: 'Philips Sonicare',
    images: ['https://picsum.photos/seed/toothbrush/300/300.jpg'],
    stock: 90,
    rating: 4.5,
    numReviews: 567,
    tags: ['toothbrush', 'electric', 'sonic', 'oral-care'],
    features: ['Sonic technology', 'Pressure sensor', '2-minute timer', 'Multiple modes'],
    aiRecommendationScore: 0.86,
    popularity: 88
  },
  {
    name: 'Yoga Mat Premium',
    description: 'Extra-thick yoga mat with alignment markers and carrying strap',
    ...calculatePrices(45),
    category: 'sports',
    brand: 'Manduka',
    images: ['https://picsum.photos/seed/yogamatpremium/300/300.jpg'],
    stock: 80,
    rating: 4.6,
    numReviews: 234,
    tags: ['yoga', 'mat', 'premium', 'alignment'],
    features: ['6mm thickness', 'Alignment markers', 'Non-slip surface', 'Carrying strap'],
    aiRecommendationScore: 0.84,
    popularity: 85
  },
  {
    name: 'Protein Powder',
    description: 'Premium whey protein powder for muscle recovery and growth',
    ...calculatePrices(4479),
    category: 'sports',
    brand: 'Optimum Nutrition',
    images: [
      'https://images.unsplash.com/photo-1590930210912-2e7c679a5932?w=400&h=400&fit=crop&crop=center',
      'https://images.pexels.com/photos/843683/pexels-photo-843683.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
      'https://cdn.pixabay.com/photo/2020/09/19/12/44/protein-5584163_960_720.jpg'
    ],
    stock: 140,
    rating: 4.3,
    numReviews: 445,
    tags: ['protein', 'whey', 'supplement', 'muscle'],
    features: ['24g protein per serving', 'BCAAs', 'Glutamine', 'Multiple flavors'],
    aiRecommendationScore: 0.81,
    popularity: 87
  },
  // Additional Electronics Products (15 more)
  {
    name: 'LG OLED TV 55"',
    description: 'Premium OLED 4K TV with perfect blacks and infinite contrast',
    ...calculatePrices(1499),
    category: 'electronics',
    brand: 'LG',
    images: ['https://picsum.photos/seed/oledtv/300/300.jpg'],
    stock: 25,
    rating: 4.8,
    numReviews: 234,
    tags: ['tv', 'oled', '4k', 'premium'],
    features: ['4K OLED display', 'Dolby Vision', 'AI Sound', 'WebOS'],
    aiRecommendationScore: 0.92,
    popularity: 89
  },
  {
    name: 'Canon EOS R6',
    description: 'Full-frame mirrorless camera with advanced autofocus',
    ...calculatePrices(2499),
    category: 'electronics',
    brand: 'Canon',
    images: ['https://picsum.photos/seed/canonr6/300/300.jpg'],
    stock: 15,
    rating: 4.7,
    numReviews: 156,
    tags: ['camera', 'mirrorless', 'full-frame', 'canon'],
    features: ['20MP sensor', '8K video', 'Dual AF', '5-axis IBIS'],
    aiRecommendationScore: 0.90,
    popularity: 85
  },
  {
    name: 'Dyson V15 Detect',
    description: 'Intelligent cordless vacuum with laser dust detection',
    ...calculatePrices(749),
    category: 'electronics',
    brand: 'Dyson',
    images: ['https://picsum.photos/seed/dysonv15/300/300.jpg'],
    stock: 30,
    rating: 4.6,
    numReviews: 189,
    tags: ['vacuum', 'cordless', 'dyson', 'smart'],
    features: ['Laser detection', 'LCD screen', '60 min runtime', 'HEPA filter'],
    aiRecommendationScore: 0.88,
    popularity: 87
  },
  {
    name: 'Samsung QLED TV 65"',
    description: 'Quantum Dot 4K TV with vibrant colors and smart features',
    ...calculatePrices(1299),
    category: 'electronics',
    brand: 'Samsung',
    images: ['https://picsum.photos/seed/qledtv/300/300.jpg'],
    stock: 20,
    rating: 4.5,
    numReviews: 145,
    tags: ['tv', 'qled', '4k', 'samsung'],
    features: ['Quantum HDR', 'Object Tracking', 'Smart TV', 'Ambient Mode'],
    aiRecommendationScore: 0.86,
    popularity: 82
  },
  {
    name: 'Sony A7 IV',
    description: 'Versatile full-frame mirrorless camera for creators',
    ...calculatePrices(2498),
    category: 'electronics',
    brand: 'Sony',
    images: ['https://picsum.photos/seed/sonya7iv/300/300.jpg'],
    stock: 18,
    rating: 4.8,
    numReviews: 167,
    tags: ['camera', 'mirrorless', 'full-frame', 'sony'],
    features: ['33MP sensor', '4K 60fps', 'S-Cinetone', '5-axis stabilization'],
    aiRecommendationScore: 0.91,
    popularity: 88
  },
  {
    name: 'Bose SoundLink Revolve',
    description: '360-degree wireless speaker with deep bass',
    ...calculatePrices(199),
    category: 'electronics',
    brand: 'Bose',
    images: ['https://picsum.photos/seed/revolve/300/300.jpg'],
    stock: 70,
    rating: 4.4,
    numReviews: 289,
    tags: ['speaker', 'bluetooth', '360', 'bose'],
    features: ['360° sound', 'IPX4 rating', '17-hour battery', 'Voice prompts'],
    aiRecommendationScore: 0.83,
    popularity: 79
  },
  {
    name: 'iPad Air 5',
    description: 'Powerful tablet with M1 chip and stunning display',
    ...calculatePrices(599),
    category: 'electronics',
    brand: 'Apple',
    images: ['https://picsum.photos/seed/ipadair5/300/300.jpg'],
    stock: 40,
    rating: 4.6,
    numReviews: 234,
    tags: ['tablet', 'apple', 'm1', 'ipad'],
    features: ['M1 chip', '10.9" display', 'Touch ID', 'All-day battery'],
    aiRecommendationScore: 0.87,
    popularity: 84
  },
  {
    name: 'Samsung Galaxy Tab S8',
    description: 'Premium Android tablet with S Pen included',
    ...calculatePrices(699),
    category: 'electronics',
    brand: 'Samsung',
    images: ['https://picsum.photos/seed/tabs8/300/300.jpg'],
    stock: 35,
    rating: 4.5,
    numReviews: 198,
    tags: ['tablet', 'samsung', 'android', 's-pen'],
    features: ['11" LCD', 'S Pen included', 'Snapdragon 8', '45W charging'],
    aiRecommendationScore: 0.85,
    popularity: 81
  },
  {
    name: 'Sonos Beam Soundbar',
    description: 'Compact smart soundbar with Alexa built-in',
    ...calculatePrices(449),
    category: 'electronics',
    brand: 'Sonos',
    images: ['https://picsum.photos/seed/beam/300/300.jpg'],
    stock: 45,
    rating: 4.3,
    numReviews: 167,
    tags: ['soundbar', 'sonos', 'alexa', 'smart'],
    features: ['Alexa built-in', 'AirPlay 2', 'HDMI ARC', 'Voice control'],
    aiRecommendationScore: 0.82,
    popularity: 78
  },
  {
    name: 'GoPro Hero 11',
    description: 'Action camera with 5.3K video and stabilization',
    ...calculatePrices(399),
    category: 'electronics',
    brand: 'GoPro',
    images: ['https://picsum.photos/seed/gopro11/300/300.jpg'],
    stock: 50,
    rating: 4.4,
    numReviews: 234,
    tags: ['camera', 'action', 'gopro', 'stabilization'],
    features: ['5.3K video', 'HyperSmooth 5.0', 'Waterproof', 'Live streaming'],
    aiRecommendationScore: 0.84,
    popularity: 83
  },
  {
    name: 'Razer Blade 15',
    description: 'Gaming laptop with RTX graphics and high refresh display',
    ...calculatePrices(1799),
    category: 'electronics',
    brand: 'Razer',
    images: ['https://picsum.photos/seed/blade15/300/300.jpg'],
    stock: 20,
    rating: 4.5,
    numReviews: 145,
    tags: ['laptop', 'gaming', 'razer', 'rtx'],
    features: ['RTX 3070', '144Hz display', 'RGB keyboard', 'Thunderbolt 4'],
    aiRecommendationScore: 0.86,
    popularity: 80
  },
  {
    name: 'DJI Mini 3 Pro',
    description: 'Lightweight drone with 4K camera and intelligent features',
    ...calculatePrices(759),
    category: 'electronics',
    brand: 'DJI',
    images: ['https://picsum.photos/seed/mini3pro/300/300.jpg'],
    stock: 25,
    rating: 4.6,
    numReviews: 189,
    tags: ['drone', 'dji', '4k', 'lightweight'],
    features: ['4K HDR video', '34 min flight', '249g weight', 'ActiveTrack'],
    aiRecommendationScore: 0.87,
    popularity: 85
  },
  {
    name: 'Amazon Echo Studio',
    description: 'High-fidelity smart speaker with 3D audio',
    ...calculatePrices(199),
    category: 'electronics',
    brand: 'Amazon',
    images: ['https://picsum.photos/seed/echostudio/300/300.jpg'],
    stock: 60,
    rating: 4.2,
    numReviews: 267,
    tags: ['speaker', 'alexa', 'smart', '3d-audio'],
    features: ['3D audio', 'Alexa built-in', 'Room adaptation', 'Zigbee hub'],
    aiRecommendationScore: 0.80,
    popularity: 76
  },
  {
    name: 'Meta Quest 2',
    description: 'All-in-one VR headset for immersive gaming',
    ...calculatePrices(299),
    category: 'electronics',
    brand: 'Meta',
    images: ['https://picsum.photos/seed/quest2/300/300.jpg'],
    stock: 40,
    rating: 4.4,
    numReviews: 345,
    tags: ['vr', 'headset', 'gaming', 'meta'],
    features: ['128GB storage', '90Hz refresh', 'Hand tracking', 'Wireless'],
    aiRecommendationScore: 0.83,
    popularity: 82
  },
  {
    name: 'Ring Video Doorbell Pro',
    description: 'Advanced video doorbell with 3D motion detection',
    ...calculatePrices(249),
    category: 'electronics',
    brand: 'Ring',
    images: ['https://picsum.photos/seed/doorbellpro/300/300.jpg'],
    stock: 35,
    rating: 4.3,
    numReviews: 223,
    tags: ['doorbell', 'video', 'security', 'ring'],
    features: ['3D motion detection', '1536p HD', 'Two-way talk', 'Pre-roll'],
    aiRecommendationScore: 0.81,
    popularity: 77
  },
  // Additional Clothing Products (28 more)
  {
    name: 'Denim Jacket',
    description: 'Classic denim jacket with modern fit and vintage wash',
    ...calculatePrices(79),
    category: 'clothing',
    brand: 'Lee',
    images: ['https://picsum.photos/seed/denimjacket/300/300.jpg'],
    stock: 90,
    rating: 4.4,
    numReviews: 234,
    tags: ['jacket', 'denim', 'lee', 'classic'],
    features: ['100% cotton denim', 'Button front', 'Chest pockets', 'Vintage wash'],
    aiRecommendationScore: 0.83,
    popularity: 81
  },
  {
    name: 'Henley Shirt',
    description: 'Comfortable henley shirt with button placket',
    ...calculatePrices(39),
    category: 'clothing',
    brand: 'J.Crew',
    images: ['https://picsum.photos/seed/henley/300/300.jpg'],
    stock: 120,
    rating: 4.2,
    numReviews: 189,
    tags: ['shirt', 'henley', 'casual', 'cotton'],
    features: ['Cotton blend', 'Button placket', 'Long sleeves', 'Regular fit'],
    aiRecommendationScore: 0.80,
    popularity: 76
  },
  {
    name: 'Chino Pants',
    description: 'Versatile chino pants for casual and business casual',
    ...calculatePrices(69),
    category: 'clothing',
    brand: 'Dockers',
    images: ['https://picsum.photos/seed/chinos/300/300.jpg'],
    stock: 100,
    rating: 4.3,
    numReviews: 267,
    tags: ['pants', 'chinos', 'dockers', 'versatile'],
    features: ['Cotton twill', 'Straight fit', 'Flat front', 'Khaki color'],
    aiRecommendationScore: 0.81,
    popularity: 78
  },
  {
    name: 'Flannel Shirt',
    description: 'Warm flannel shirt perfect for cold weather',
    ...calculatePrices(59),
    category: 'clothing',
    brand: 'L.L.Bean',
    images: ['https://picsum.photos/seed/flannel/300/300.jpg'],
    stock: 80,
    rating: 4.5,
    numReviews: 345,
    tags: ['shirt', 'flannel', 'warm', 'plaid'],
    features: ['100% cotton flannel', 'Brushed finish', 'Button front', 'Plaid pattern'],
    aiRecommendationScore: 0.84,
    popularity: 83
  },
  {
    name: 'V-Neck Sweater',
    description: 'Classic v-neck sweater in merino wool',
    ...calculatePrices(89),
    category: 'clothing',
    brand: 'Banana Republic',
    images: ['https://picsum.photos/seed/vneck/300/300.jpg'],
    stock: 60,
    rating: 4.4,
    numReviews: 156,
    tags: ['sweater', 'v-neck', 'merino', 'classic'],
    features: ['Merino wool', 'V-neck design', 'Ribbed trim', 'Machine washable'],
    aiRecommendationScore: 0.83,
    popularity: 79
  },
  {
    name: 'Dress Shirt',
    description: 'Professional dress shirt with non-iron finish',
    ...calculatePrices(49),
    category: 'clothing',
    brand: 'Brooks Brothers',
    images: ['https://picsum.photos/seed/dressshirt/300/300.jpg'],
    stock: 150,
    rating: 4.1,
    numReviews: 423,
    tags: ['shirt', 'dress', 'professional', 'non-iron'],
    features: ['Non-iron cotton', 'Spread collar', 'French cuffs', 'Tailored fit'],
    aiRecommendationScore: 0.79,
    popularity: 74
  },
  {
    name: 'Cardigan Sweater',
    description: 'Cozy cardigan sweater with pockets',
    ...calculatePrices(79),
    category: 'clothing',
    brand: 'Gap',
    images: ['https://picsum.photos/seed/cardigan/300/300.jpg'],
    stock: 70,
    rating: 4.3,
    numReviews: 198,
    tags: ['sweater', 'cardigan', 'cozy', 'pockets'],
    features: ['Cotton blend', 'Open front', 'Side pockets', 'Long sleeves'],
    aiRecommendationScore: 0.81,
    popularity: 77
  },
  {
    name: 'Track Pants',
    description: 'Comfortable track pants for athletic activities',
    ...calculatePrices(45),
    category: 'clothing',
    brand: 'Adidas',
    images: ['https://picsum.photos/seed/trackpants/300/300.jpg'],
    stock: 140,
    rating: 4.2,
    numReviews: 267,
    tags: ['pants', 'track', 'athletic', 'adidas'],
    features: ['Polyester blend', 'Elastic waist', 'Side stripes', 'Slim fit'],
    aiRecommendationScore: 0.80,
    popularity: 75
  },
  {
    name: 'Tank Top',
    description: 'Breathable tank top for workouts and casual wear',
    ...calculatePrices(25),
    category: 'clothing',
    brand: 'Nike',
    images: ['https://picsum.photos/seed/tanktop/300/300.jpg'],
    stock: 180,
    rating: 4.1,
    numReviews: 334,
    tags: ['tank', 'workout', 'breathable', 'nike'],
    features: ['Dri-FIT fabric', 'Athletic cut', 'Lightweight', 'Quick-drying'],
    aiRecommendationScore: 0.78,
    popularity: 72
  },
  {
    name: 'Blazer Jacket',
    description: 'Professional blazer for business and formal occasions',
    ...calculatePrices(149),
    category: 'clothing',
    brand: 'Hugo Boss',
    images: ['https://picsum.photos/seed/blazer/300/300.jpg'],
    stock: 40,
    rating: 4.6,
    numReviews: 145,
    tags: ['blazer', 'business', 'formal', 'boss'],
    features: ['Wool blend', 'Notch lapels', 'Two-button closure', 'Tailored fit'],
    aiRecommendationScore: 0.86,
    popularity: 84
  },
  {
    name: 'Polo Dress',
    description: 'Elegant polo dress for casual and semi-formal wear',
    ...calculatePrices(89),
    category: 'clothing',
    brand: 'Tommy Hilfiger',
    images: ['https://picsum.photos/seed/polodress/300/300.jpg'],
    stock: 50,
    rating: 4.4,
    numReviews: 189,
    tags: ['dress', 'polo', 'casual', 'elegant'],
    features: ['Pique cotton', 'A-line silhouette', 'Collared neckline', 'Side slits'],
    aiRecommendationScore: 0.83,
    popularity: 80
  },
  {
    name: 'Leggings',
    description: 'High-waisted leggings for yoga and everyday comfort',
    ...calculatePrices(55),
    category: 'clothing',
    brand: 'Lululemon',
    images: ['https://picsum.photos/seed/leggings/300/300.jpg'],
    stock: 130,
    rating: 4.5,
    numReviews: 456,
    tags: ['leggings', 'yoga', 'high-waisted', 'comfortable'],
    features: ['Nulu fabric', 'High-waisted', 'Four-way stretch', 'Hidden pocket'],
    aiRecommendationScore: 0.85,
    popularity: 87
  },
  {
    name: 'Crew Neck Sweatshirt',
    description: 'Classic crew neck sweatshirt in fleece fabric',
    ...calculatePrices(65),
    category: 'clothing',
    brand: 'Champion',
    images: ['https://picsum.photos/seed/crewsweat/300/300.jpg'],
    stock: 110,
    rating: 4.3,
    numReviews: 278,
    tags: ['sweatshirt', 'crew', 'fleece', 'champion'],
    features: ['Heavyweight fleece', 'Ribbed cuffs', 'Classic fit', 'Embroidered logo'],
    aiRecommendationScore: 0.81,
    popularity: 78
  },
  {
    name: 'Button-Up Shirt',
    description: 'Casual button-up shirt with modern fit',
    ...calculatePrices(55),
    category: 'clothing',
    brand: 'Uniqlo',
    images: ['https://picsum.photos/seed/buttonup/300/300.jpg'],
    stock: 160,
    rating: 4.2,
    numReviews: 389,
    tags: ['shirt', 'button-up', 'casual', 'modern'],
    features: ['Cotton poplin', 'Modern fit', 'Spread collar', 'Machine washable'],
    aiRecommendationScore: 0.80,
    popularity: 76
  },
  {
    name: 'Puffer Vest',
    description: 'Lightweight puffer vest for layering',
    ...calculatePrices(75),
    category: 'clothing',
    brand: 'Patagonia',
    images: ['https://picsum.photos/seed/puffervest/300/300.jpg'],
    stock: 45,
    rating: 4.4,
    numReviews: 167,
    tags: ['vest', 'puffer', 'lightweight', 'patagonia'],
    features: ['Recycled polyester', 'Insulated', 'Zippered pockets', 'Packable'],
    aiRecommendationScore: 0.83,
    popularity: 81
  },
  {
    name: 'Yoga Pants',
    description: 'High-performance yoga pants with moisture-wicking fabric',
    ...calculatePrices(68),
    category: 'clothing',
    brand: 'Athleta',
    images: ['https://picsum.photos/seed/yogapants/300/300.jpg'],
    stock: 95,
    rating: 4.5,
    numReviews: 334,
    tags: ['yoga', 'pants', 'performance', 'moisture-wicking'],
    features: ['Performance fabric', 'High waist', 'Flat seams', 'Hidden pocket'],
    aiRecommendationScore: 0.84,
    popularity: 85
  },
  {
    name: 'Casual Shorts',
    description: 'Comfortable cotton shorts for everyday wear',
    ...calculatePrices(35),
    category: 'clothing',
    brand: 'Old Navy',
    images: ['https://picsum.photos/seed/casualshorts/300/300.jpg'],
    stock: 200,
    rating: 4.1,
    numReviews: 445,
    tags: ['shorts', 'casual', 'cotton', 'comfortable'],
    features: ['100% cotton', 'Elastic waist', 'Side pockets', 'Above knee length'],
    aiRecommendationScore: 0.78,
    popularity: 73
  },
  {
    name: 'Turtleneck Sweater',
    description: 'Classic turtleneck sweater in fine knit',
    ...calculatePrices(95),
    category: 'clothing',
    brand: 'Everlane',
    images: ['https://picsum.photos/seed/turtleneck/300/300.jpg'],
    stock: 35,
    rating: 4.6,
    numReviews: 134,
    tags: ['sweater', 'turtleneck', 'classic', 'fine-knit'],
    features: ['Fine gauge knit', 'Ribbed cuffs', 'Slim fit', 'Machine washable'],
    aiRecommendationScore: 0.85,
    popularity: 82
  },
  {
    name: 'Windbreaker Jacket',
    description: 'Lightweight windbreaker for outdoor activities',
    ...calculatePrices(59),
    category: 'clothing',
    brand: 'The North Face',
    images: ['https://picsum.photos/seed/windbreaker/300/300.jpg'],
    stock: 75,
    rating: 4.3,
    numReviews: 223,
    tags: ['jacket', 'windbreaker', 'lightweight', 'outdoor'],
    features: ['Water-resistant', 'Packable', 'Adjustable hood', 'Ventilation'],
    aiRecommendationScore: 0.81,
    popularity: 77
  },
  {
    name: 'Dress Pants',
    description: 'Professional dress pants with modern fit',
    ...calculatePrices(85),
    category: 'clothing',
    brand: 'Calvin Klein',
    images: ['https://picsum.photos/seed/dresspants/300/300.jpg'],
    stock: 65,
    rating: 4.2,
    numReviews: 189,
    tags: ['pants', 'dress', 'professional', 'modern'],
    features: ['Wool blend', 'Flat front', 'Straight leg', 'Unhemmed'],
    aiRecommendationScore: 0.80,
    popularity: 75
  },
  {
    name: 'Graphic T-Shirt',
    description: 'Trendy graphic t-shirt with unique designs',
    ...calculatePrices(32),
    category: 'clothing',
    brand: 'Urban Outfitters',
    images: ['https://picsum.photos/seed/graphictee/300/300.jpg'],
    stock: 140,
    rating: 4.0,
    numReviews: 267,
    tags: ['t-shirt', 'graphic', 'trendy', 'unique'],
    features: ['100% cotton', 'Graphic print', 'Regular fit', 'Pre-shrunk'],
    aiRecommendationScore: 0.77,
    popularity: 71
  },
  {
    name: 'Knit Hat',
    description: 'Warm knit hat for cold weather',
    ...calculatePrices(28),
    category: 'clothing',
    brand: 'Carhartt',
    images: ['https://picsum.photos/seed/knithat/300/300.jpg'],
    stock: 180,
    rating: 4.4,
    numReviews: 345,
    tags: ['hat', 'knit', 'warm', 'winter'],
    features: ['Acrylic knit', 'Fold-up cuff', 'Stretch fit', 'Embroidered logo'],
    aiRecommendationScore: 0.82,
    popularity: 79
  },
  {
    name: 'Leather Belt',
    description: 'Genuine leather belt with classic buckle',
    ...calculatePrices(45),
    category: 'clothing',
    brand: 'Timberland',
    images: ['https://picsum.photos/seed/leatherbelt/300/300.jpg'],
    stock: 90,
    rating: 4.5,
    numReviews: 156,
    tags: ['belt', 'leather', 'classic', 'timberland'],
    features: ['Genuine leather', 'Classic buckle', '1.5" width', 'Adjustable'],
    aiRecommendationScore: 0.84,
    popularity: 83
  },
  {
    name: 'Socks Pack',
    description: 'Multi-pack of comfortable cotton socks',
    ...calculatePrices(19),
    category: 'clothing',
    brand: 'Hanes',
    images: ['https://picsum.photos/seed/socks/300/300.jpg'],
    stock: 300,
    rating: 4.1,
    numReviews: 567,
    tags: ['socks', 'cotton', 'multi-pack', 'comfortable'],
    features: ['Cotton blend', 'Cushioned foot', 'Arch support', '6 pairs'],
    aiRecommendationScore: 0.79,
    popularity: 74
  },
  {
    name: 'Scarf',
    description: 'Soft wool scarf for winter warmth',
    ...calculatePrices(38),
    category: 'clothing',
    brand: 'Burberry',
    images: ['https://picsum.photos/seed/scarf/300/300.jpg'],
    stock: 55,
    rating: 4.7,
    numReviews: 123,
    tags: ['scarf', 'wool', 'winter', 'burberry'],
    features: ['100% wool', 'Classic check', 'Fringe edges', 'Hand washable'],
    aiRecommendationScore: 0.86,
    popularity: 86
  },
  {
    name: 'Baseball Cap',
    description: 'Classic adjustable baseball cap',
    ...calculatePrices(22),
    category: 'clothing',
    brand: 'New Era',
    images: ['https://picsum.photos/seed/baseballcap/300/300.jpg'],
    stock: 160,
    rating: 4.2,
    numReviews: 234,
    tags: ['cap', 'baseball', 'adjustable', 'new-era'],
    features: ['Cotton twill', 'Structured fit', 'Adjustable strap', 'Embroidered logo'],
    aiRecommendationScore: 0.80,
    popularity: 76
  },
  {
    name: 'Leather Wallet',
    description: 'Genuine leather bifold wallet',
    ...calculatePrices(58),
    category: 'clothing',
    brand: 'Fossil',
    images: ['https://picsum.photos/seed/wallet/300/300.jpg'],
    stock: 70,
    rating: 4.4,
    numReviews: 189,
    tags: ['wallet', 'leather', 'bifold', 'fossil'],
    features: ['Genuine leather', 'RFID blocking', 'Multiple card slots', 'Bill compartment'],
    aiRecommendationScore: 0.83,
    popularity: 80
  }
];

// Sample user data
const sampleUsers = [
  {
    name: 'John Doe',
    email: 'john.doe@example.com',
    password: 'password123',
    avatar: 'https://picsum.photos/seed/johndoe/100/100.jpg',
    preferences: {
      categories: ['electronics', 'sports'],
      brands: ['Apple', 'Nike'],
      priceRange: { min: 50, max: 1000 }
    },
    aiProfile: {
      interests: ['technology', 'fitness', 'photography'],
      personalityTraits: ['tech-savvy', 'active', 'quality-conscious'],
      recommendationWeights: {
        price: 0.2,
        brand: 0.3,
        category: 0.3,
        popularity: 0.2
      }
    }
  },
  {
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    password: 'password123',
    avatar: 'https://picsum.photos/seed/janesmith/100/100.jpg',
    preferences: {
      categories: ['clothing', 'beauty', 'home'],
      brands: ['Nike', 'NatureGlow', 'BasicWear'],
      priceRange: { min: 20, max: 300 }
    },
    aiProfile: {
      interests: ['fashion', 'skincare', 'home decor', 'sustainability'],
      personalityTraits: ['fashion-conscious', 'eco-friendly', 'budget-aware'],
      recommendationWeights: {
        price: 0.4,
        brand: 0.2,
        category: 0.2,
        popularity: 0.2
      }
    }
  },
  {
    name: 'Mike Johnson',
    email: 'mike.johnson@example.com',
    password: 'password123',
    avatar: 'https://picsum.photos/seed/mikejohnson/100/100.jpg',
    preferences: {
      categories: ['electronics', 'books', 'toys'],
      brands: ['Sony', 'Penguin Classics', 'LEGO'],
      priceRange: { min: 10, max: 500 }
    },
    aiProfile: {
      interests: ['gaming', 'reading', 'collectibles', 'audio'],
      personalityTraits: ['enthusiast', 'collector', 'quality-focused'],
      recommendationWeights: {
        price: 0.3,
        brand: 0.4,
        category: 0.2,
        popularity: 0.1
      }
    }
  },
  {
    name: 'Sarah Williams',
    email: 'sarah.williams@example.com',
    password: 'password123',
    avatar: 'https://picsum.photos/seed/sarahwilliams/100/100.jpg',
    preferences: {
      categories: ['home', 'beauty', 'clothing'],
      brands: ['SmartHome', 'NatureGlow', 'Adidas'],
      priceRange: { min: 30, max: 400 }
    },
    aiProfile: {
      interests: ['smart home', 'organic products', 'comfort', 'wellness'],
      personalityTraits: ['health-conscious', 'modern', 'comfort-seeking'],
      recommendationWeights: {
        price: 0.3,
        brand: 0.2,
        category: 0.3,
        popularity: 0.2
      }
    }
  },
  {
    name: 'David Brown',
    email: 'david.brown@example.com',
    password: 'password123',
    avatar: 'https://picsum.photos/seed/davidbrown/100/100.jpg',
    preferences: {
      categories: ['sports', 'electronics'],
      brands: ['FitGear', 'Apple', 'Samsung'],
      priceRange: { min: 100, max: 2000 }
    },
    aiProfile: {
      interests: ['fitness', 'outdoor activities', 'technology', 'performance'],
      personalityTraits: ['athletic', 'adventurous', 'performance-driven'],
      recommendationWeights: {
        price: 0.1,
        brand: 0.4,
        category: 0.3,
        popularity: 0.2
      }
    }
  }
];

async function seedDatabase() {
  try {
    // Connect to MongoDB Atlas
    const mongoURI = process.env.MONGODB_URI || 'mongodb://localhost:27017/ai-ecommerce';
    const mongoOptions = {
      maxPoolSize: 10,
      serverSelectionTimeoutMS: 5000,
      socketTimeoutMS: 45000,
    };
    
    await mongoose.connect(mongoURI, mongoOptions);
    console.log('✅ Connected to MongoDB Atlas');

    // Clear existing data
    await Product.deleteMany({});
    await User.deleteMany({});
    console.log('Cleared existing data');

    // Hash passwords and create users
    const usersWithHashedPasswords = await Promise.all(
      sampleUsers.map(async (user) => {
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(user.password, salt);
        return { ...user, password: hashedPassword };
      })
    );

    // Insert users
    const createdUsers = await User.insertMany(usersWithHashedPasswords);
    console.log(`Created ${createdUsers.length} users`);

    // Add seller to each product
    const productsWithSeller = sampleProducts.map(product => ({
      ...product,
      seller: createdUsers[0]._id // Use first user as seller
    }));

    // Insert products
    const createdProducts = await Product.insertMany(productsWithSeller);
    console.log(`Created ${createdProducts.length} products`);

    // Add some sample reviews
    const reviews = [
      {
        user: createdUsers[0]._id,
        name: 'John Doe',
        rating: 5,
        comment: 'Amazing product! Exactly what I was looking for.'
      },
      {
        user: createdUsers[1]._id,
        name: 'Jane Smith',
        rating: 4,
        comment: 'Good quality, but shipping took a while.'
      }
    ];

    // Add reviews to first few products
    for (let i = 0; i < Math.min(5, createdProducts.length); i++) {
      await Product.findByIdAndUpdate(createdProducts[i]._id, {
        $push: { reviews: { $each: reviews } }
      });
    }

    console.log('Added sample reviews');
    console.log('Database seeded successfully!');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
